//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Web App allows users to add Properties for sale or rent with the addition of each
        ///                     Required details and then display directly and keep track of the real estate to reach the largest number of people.
        /// </summary>
        internal static string Akaratak_Desc {
            get {
                return ResourceManager.GetString("Akaratak_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction contracts for hotels  ,offices fronts .
        /// </summary>
        internal static string BDCO_Desc {
            get {
                return ResourceManager.GetString("BDCO_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check It.
        /// </summary>
        internal static string Check_it {
            get {
                return ResourceManager.GetString("Check_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apper Tech ©.
        /// </summary>
        internal static string Company_Ltd {
            get {
                return ResourceManager.GetString("Company_Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        internal static string Company_Ltd_Desc {
            get {
                return ResourceManager.GetString("Company_Ltd_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have any Ideas, Projects, Suggestions or comments? we highly encourage you to send them to us!.
        /// </summary>
        internal static string Contact_Us_Desc {
            get {
                return ResourceManager.GetString("Contact_Us_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creativity.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With our first Model for Real Estate Already online we are Moving to grow in all of the virtual market, adding more models for public services.
        /// </summary>
        internal static string Create_Desc {
            get {
                return ResourceManager.GetString("Create_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string Email_Holder {
            get {
                return ResourceManager.GetString("Email_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - Services.
        /// </summary>
        internal static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide a noble service to society by collecting the waste vegetable oil and send to biodiesel plants, soap factories, and different other industries, which contributes to maintaining a clean and healthy environment and helps in cutting down on the natural resources consumption..
        /// </summary>
        internal static string Hajer_Desc {
            get {
                return ResourceManager.GetString("Hajer_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Work.
        /// </summary>
        internal static string HardWork {
            get {
                return ResourceManager.GetString("HardWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With our highly trained staff of employee’s tech and managers we are able to create any project with high quality and assured customer satisfaction.
        /// </summary>
        internal static string HardWork_Desc {
            get {
                return ResourceManager.GetString("HardWork_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto in-Time Investment Collaboration Ethereum ÐApp
        ///The ÐApp aims to elect top investment wallets. The elections run continuously, one election at a time.
        /// </summary>
        internal static string InvestorX_Desc {
            get {
                return ResourceManager.GetString("InvestorX_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Vacancies.
        /// </summary>
        internal static string Job_Vacancies {
            get {
                return ResourceManager.GetString("Job_Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Positions At Apper Tech.
        /// </summary>
        internal static string Job_Vacancies_Intro {
            get {
                return ResourceManager.GetString("Job_Vacancies_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        internal static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Somthing for us.
        /// </summary>
        internal static string Message_Holder {
            get {
                return ResourceManager.GetString("Message_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        internal static string Name_Holder {
            get {
                return ResourceManager.GetString("Name_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Highlights.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Morphological Analyzer and Expert Part-Of-Speech Tagger The Core of a Framework for Arabic Language Proccessing as an Expert System.
        /// </summary>
        internal static string Qutuf_Desc {
            get {
                return ResourceManager.GetString("Qutuf_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apper Tech.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public web Solutions and Services Company.
        /// </summary>
        internal static string SiteSlogan {
            get {
                return ResourceManager.GetString("SiteSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web and Mobile development - Applications and e-Services.
        /// </summary>
        internal static string SiteSlogan_Desc {
            get {
                return ResourceManager.GetString("SiteSlogan_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App&lt;span&gt;er&lt;/span&gt; Tech.
        /// </summary>
        internal static string SiteSlogan_Title {
            get {
                return ResourceManager.GetString("SiteSlogan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Using Dynamic Data Framework, we can Implement Complex and Productive apps in the shortest amount of time and most client first features.
        /// </summary>
        internal static string Speed_Desc {
            get {
                return ResourceManager.GetString("Speed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Subject?.
        /// </summary>
        internal static string Supject_Holder {
            get {
                return ResourceManager.GetString("Supject_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Opinion Mining and Rewarding ÐApp
        ///The ÐApp aims to facilitate crowd opinion mining through incentivization with rewards..
        /// </summary>
        internal static string SurveyX_Desc {
            get {
                return ResourceManager.GetString("SurveyX_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The People Responsable of the company and production.
        /// </summary>
        internal static string Team_Desc {
            get {
                return ResourceManager.GetString("Team_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apper Tech.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
